/*
	GadgetReactor.h
	(c)1999 PaleStar Development, Richard Lyle
*/

#ifndef GADGET_REACTOR_H
#define GADGET_REACTOR_H

#include "NounGadget.h"
#include "GameDll.h"

//----------------------------------------------------------------------------

class DLL GadgetReactor : public NounGadget
{
public:
	DECLARE_WIDGET_CLASS();
	DECLARE_PROPERTY_LIST();

	// Construction
	GadgetReactor();
	// Noun interface
	void					setup();
	void					initialize();
	// NounGadget interface
	Type					type() const;					// get gadget type
	EnergyClass				energyClass() const;

	int						addMaxEnergy() const;
	float					addSignature() const;
	virtual CharString		useTip( Noun * pTarget,
								bool shift ) const;	

	bool					usable( Noun * pTarget, 
								bool shift ) const;			// can gadget be used on target
	bool					useActive() const;				// is the gadget current on or off
	void					use( dword when, Noun * pTarget,
								bool shift);				// use gadget
	int						useEnergy( dword nTick, 
								int energy );

	// Accessors
	virtual int				maxEnergy() const = 0;			// max energy added by this reactor
	virtual int				energyGenerated() const = 0;				// energy generated by this reactor
	virtual float			signature() const = 0;			// how much signature does this gadget add

	bool					active() const;

private:
};

//----------------------------------------------------------------------------

inline bool GadgetReactor::active() const
{
	return (flags() & FLAG_ACTIVE) != 0;
}

//----------------------------------------------------------------------------



#endif

//----------------------------------------------------------------------------
// EOF
