//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Universe.rc
//
#define IDS_AND                         2
#define IDS_NO_MISSIONS                 11
#define IDS_SENT_CREDITS                12
#define IDS_RECV_CREDITS                13
#define IDS_MISSION_COMPLETE            14
#define IDS_MISSION_FAILED              15
#define IDS_MISSION_ABORTED             16
#define IDS_MISSION_ASSIGNED            17
#define IDS_MISSION_REPAIR              18
#define IDS_MISSION_REPAIR_DESC         19
#define IDS_MISSION_DEFEND              20
#define IDS_MISSION_DEFEND_DESC         21
#define IDS_MISSION_ESCORT              22
#define IDS_MISSION_ESCORT_DESC         23
#define IDS_MISSION_CAPTURE             24
#define IDS_MISSION_CAPTURE_DESC        25
#define IDS_MISSION_SCOUT               28
#define IDS_MISSION_SCOUT_DESC          29
#define IDS_DISTRESS_INVADED            30
#define IDS_DISTRESS_ATTACKED           31
#define IDS_DISTRESS_SUPPLY             32
#define IDS_SELF_DESTRUCT_ABORTED       33
#define IDS_SELF_DESTRUCT_CONFIRM       34
#define IDS_SELF_DESTRUCT               35
#define IDS_MISSION_REQUEST             36
#define IDS_SCRAP                       37
#define IDS_DISBAND                     38
#define IDS_NO_DEPOT                    39
#define IDS_NO_JUMPGATE                 40
#define IDS_NO_PORT                     41
#define IDS_NO_YARD                     42
#define IDS_TIP_YARD                    43
#define IDS_CONFIRM_YARD                44
#define IDS_NO_DISTRESS                 45
#define IDS_BREAKING_ORBIT              46
#define IDS_COMMAND_ORBIT               47
#define IDS_COMMAND_FOLLOW              48
#define IDS_COMMAND_DOCK                49
#define IDS_ENTER_SAFE_ZONE             50
#define IDS_DOCKED_WITH                 51
#define IDS_UNDOCK                      52
#define IDS_LEAVING_SAFE_ZONE           53
#define IDS_JUMP_ALIGNMENT              54
#define IDS_JUMPING                     55
#define IDS_JUMP_ABORTED                56
#define IDS_JUMP_COMPLETE               57
#define IDS_JUMP_ENGAGED                58
#define IDS_JUMP_ALIGN                  59
#define IDS_JUMP_ALIGN_ABORTED          60
#define IDS_JUMP_NO_FUEL                61
#define IDS_RELOADING                   62
#define IDS_RELOAD_ABORT                63
#define IDS_RELOAD_SELF                 64
#define IDS_RELOAD_STOP                 65
#define IDS_GADGET_ACTIVE               66
#define IDS_GADGET_INACTIVE             67
#define IDS_GADGET_LOW_ENERGY           68
#define IDS_FIGHTERS_RECALLED           69
#define IDS_GADGET_DESTROYED            70
#define IDS_BUILDING                    71
#define IDS_BUILD_ABORT                 72
#define IDS_BUILD_COMPLETE              73
#define IDS_TRADE_BUY                   74
#define IDS_TRADE_SELL                  75
#define IDS_STRUCTURE_ACTIVE            76
#define IDS_STRUCTURE_INACTIVE          77
#define IDS_STRUCTURE_SCRAPPED          78
#define IDS_PLANET_REVOLT               79
#define IDS_RESEARCH                    80
#define IDS_RESEARCH_STOPPED            81
#define IDS_NOT_ENOUGH_CARGO            82
#define IDS_INSTALL_GADGET              83
#define IDS_REFIT_GADGET                84
#define IDS_NEWS_PLAGUE                 85
#define IDS_NEWS_UNREST                 86
#define IDS_NEWS_RESESSION              87
#define IDS_NEWS_STRIKE                 88
#define IDS_NEWS_BOOM                   89
#define IDS_NEWS_SMUGGLER               90
#define IDS_NEWS_MINING_FIND            91
#define IDS_NEWS_FOOD_SHORT             92
#define IDS_NEWS_POWER_SHORT            93
#define IDS_NEWS_WORKER_SHORT           94
#define IDS_NEWS_PLAGUE_END             95
#define IDS_NEWS_UNREST_END             96
#define IDS_NEWS_RESESSION_END          97
#define IDS_NEWS_STRIKE_END             98
#define IDS_NEWS_BOOM_END               99
#define IDS_NEWS_SMUGGLER_END           100
#define IDS_NEWS_MINING_FIND_END        101
#define IDS_NEWS_FOOD_SHORT_END         102
#define IDS_NEWS_POWER_SHORT_END        103
#define IDS_NEWS_WORKER_SHORT_END       104
#define IDS_RECEIVED_ORDER              105
#define IDS_ORBITING                    106
#define IDS_SELF_DESTRUCTED             107
#define IDS_DESTROYED_BY                108
#define IDS_DESTROYED                   109
#define IDS_SHIP_CAPTURED               110
#define IDS_PLANET_CAPTURED             111
#define IDS_FACTORY_BUILDING            112
#define IDS_FACTORY_NO_PORT             113
#define IDS_DEFENSE_ENERGY              114
#define IDS_DEFENSE_SHIELDING           115
#define IDS_BARRACKS_TRAINING           116
#define IDS_BARRACKS_STOPPED            117
#define IDS_STRUCTURE_WORKERS           118
#define IDS_STRUCTURE_POWER             119
#define IDS_STRUCTURE_FOOD              120
#define IDS_STRUCTURE_HABITAT           121
#define IDS_STRUCTURE_MINING            122
#define IDS_STRUCTURE_RESEARCH          123
#define IDS_STRUCTURE_WOKER_SHORT       124
#define IDS_STRUCTURE_POWER_SHORT       125
#define IDS_STRUCTURE_DAMAGE            126
#define IDS_STRUCTURE_BUILDING          127
#define IDS_PLANET_COLONY_DESTROYED     128
#define IDS_GADGET_DAMAGE               129
#define IDS_GADGET_MOUNT                130
#define IDS_BEACON_NAME                 131
#define IDS_SLOT_INSTALL                132
#define IDS_SLOT_TIP                    133
#define IDS_SHIELDS_DEACTIVATE          134
#define IDS_SHIELDS_ACTIVATE            135
#define IDS_SHIELDS_REINFORCE           136
#define IDS_UNLOADING                   137
#define IDS_JETTISONED                  138
#define IDS_LOADING                     139
#define IDS_CONSTRUCTED                 140
#define IDS_NO_ENEMY                    141
#define IDS_NO_FRIENDLY                 142
#define IDS_CONFIRM_JETTISON            143
#define IDS_NEWS_STAR_CONTROL           144
#define IDS_PRESTIGE_BONUS              145
#define IDS_RESEARCHING                 146
#define IDS_ACTIVE                      147
#define IDS_INACTIVE                    148
#define IDS_RUNNING_SCRIPT              149
#define IDS_SPAWN                       150
#define IDS_LATENCY_TICK_OFFSET         151
#define IDS_SHIP_ZONEID                 152
#define IDS_TARGET_ZONEID               153
#define IDS_FAILED_CONNECT_META         154
#define IDS_CONNECTED_META              155
#define IDS_PLAYING_ON                  156
#define IDS_ACCOUNT_BANNED              157
#define IDS_FAILED_LOGIN_META           158
#define IDS_SERVER_CONNECTION_BPS       159
#define IDS_FAILED_RECONNECT_META       160
#define IDS_FAILED_LOGIN_META_CLOSING   161
#define IDS_FAILED_SELECT_GAME          162
#define IDS_HAS_BEEN_X_TO               163
#define IDS_PROMOTED                    164
#define IDS_DEMOTED                     165
#define IDS_AWARDED_BADGE               166
#define IDS_HAS_BEEN_AWARDED            167
#define IDS_INSUFFICIENT_RESOURCES      168
#define IDS_SPAWN_NOT_FOUND             169
#define IDS_INSUFFICIENT_RANK_BADGES    170
#define IDS_SHIP_NOT_FOUND              171
#define IDS_UNIVERSE_SHUTTING_DOWN      172
#define IDS_RANK_EXCEEDS_MAXIMUM        173
#define IDS_SERVER_NOT_TRUSTED          174
#define IDS_STORAGE_FULL                175
#define IDS_INVALID_FLEET               176
#define IDS_FLEET_IS_LOCKED             177
#define IDS_FLEET_IS_FULL               178
#define IDS_SHIP_ALREADY_SPAWNED        179
#define IDS_ZONE_IS_OFFLINE             181
#define IDS_CANNOT_USE_SHIP             182
#define IDS_MAXIMUM_SHIPS_ACTIVE        183
#define IDS_REMOVE_GADGET               184
#define IDS_JOINED_FLEET_X              185
#define IDS_SHIP_NOT_AVAILABLE          186
#define IDS_INVALID_SPAWN               188
#define IDS_INSUFFICIENT_TECHNOLOGY     189
#define IDS_SHIP_BOARDED                190
#define IDS_CARGO_FULL                  191
#define IDS_SENDING_ORDER               192
#define IDS_NO_ORDER                    193
#define IDS_WORMHOLE_FAILED             194
#define IDS_X_ENEMY_CONTROL             195
#define IDS_NEWS_ENEMY                  196
#define IDS_NEWS_BLOCKADE               197
#define IDS_NEWS_BLOCKADE_END           198
#define IDS_SHIP_DOCKED_X               199
#define IDS_SET_FOCUS                   200
#define IDS_INTERDICTOR                 201
#define IDC_PROGRESS1                   4000
#define IDD_CLIENT_UPDATE               4000
#define IDC_PROGRESS2                   4001
#define IDI_ICON1                       4001
#define IDC_FILESTATUS                  4002
#define IDC_STATUS                      4003
#define IDD_DIALOG1                     4003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4005
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         4003
#define _APS_NEXT_SYMED_VALUE           4000
#endif
#endif
